### ISSUE TITLE
FairyGUI-Phaser是否可以配套官方的Phaser 3一起使用呢？

### ISSUE THREAD

**Issue by ant642507com** [ApowoGames/FairyGUI-Phaser#27]
FairyGUI-Phaser是否可以配套官方的Phaser 3一起使用呢？

定制化Phaser 3 和 官方的区别在哪里？

后续是否有支持官方Phaser 3 的计划？

**Comment by akeboshi1** [comment]
> FairyGUI-Phaser是否可以配套官方的Phaser 3一起使用呢？
> 
> 定制化Phaser 3 和 官方的区别在哪里？
> 
> 后续是否有支持官方Phaser 3 的计划？

定制的phaser大概改了以下几个地方：
- 移除了物理引擎，facebook插件
- 调整了显示对象remove的逻辑(官方在移除对象时，会将对象添加到scene场景上，这逻辑会影响fairy对象的添加和移除逻辑)


UI插件会一直维护，后续也会持续跟进官方的版本
