### ISSUE TITLE
list item回收问题

### ISSUE THREAD

**Issue by 2505817596** [ApowoGames/FairyGUI-Phaser#3]
如图,当我调用 list.removeChildToPool(c)的时候,这个回收的item没有消失,位置也莫名其妙的到了左上角
![Snipaste_2022-04-13_02-43-26](https://user-images.githubusercontent.com/37748815/163031972-30d08f81-2da9-4d0c-b731-4e1f1c539530.png)
然后第二个问题,当我滚动列表的时候,有时候没在视口的item也会莫名奇妙的出现在左边
![Snipaste_2022-04-13_02-40-52](https://user-images.githubusercontent.com/37748815/163032336-bd202cfd-9162-4f5d-a089-1cf69f094fe3.png)
请问下这是哪里出问题了吗

**Comment by akeboshi1** [comment]
> 如图,当我调用 list.removeChildToPool(c)的时候,这个回收的item没有消失,位置也莫名其妙的到了左上角 ![Snipaste_2022-04-13_02-43-26](https://user-images.githubusercontent.com/37748815/163031972-30d08f81-2da9-4d0c-b731-4e1f1c539530.png) 然后第二个问题,当我滚动列表的时候,有时候没在视口的item也会莫名奇妙的出现在左边 ![Snipaste_2022-04-13_02-40-52](https://user-images.githubusercontent.com/37748815/163032336-bd202cfd-9162-4f5d-a089-1cf69f094fe3.png) 请问下这是哪里出问题了吗

你好，这个问题，实质上是phaser在移除对象的时候做的一个处理，当子对象移除时便会添加到scene的显示队列中
![image](https://user-images.githubusercontent.com/18412751/163324318-963a51e5-79dc-40a1-8200-f92902927275.png)，
我这边是修改了phaser的代码，这样移除便是真正从场景移除
抱歉，最近比较忙，没及时回复你的issure，忘见谅
