### ISSUE TITLE
输入框文本适配时遇到的问题

### ISSUE THREAD

**Issue by 2505817596** [ApowoGames/FairyGUI-Phaser#4]
1.提示文本导出不成功,得代码指定
2.输入看不到文字
![demo](https://user-images.githubusercontent.com/37748815/163719564-28540829-fad3-44d4-9385-231ef59aecef.gif)

**Comment by akeboshi1** [comment]
> 1.提示文本导出不成功,得代码指定 2.输入看不到文字 ![demo](https://user-images.githubusercontent.com/37748815/163719564-28540829-fad3-44d4-9385-231ef59aecef.gif)

提供下项目资源和demo 或代码

**Comment by 2505817596** [comment]
[test.zip](https://github.com/ApowoGames/FairyGUI-Phaser/files/8509276/test.zip)

**Comment by 2505817596** [comment]
> > 1.提示文本导出不成功,得代码指定 2.输入看不到文字 ![demo](https://user-images.githubusercontent.com/37748815/163719564-28540829-fad3-44d4-9385-231ef59aecef.gif)
> 
> 提供下项目资源和demo 或代码
[test.zip](https://github.com/ApowoGames/FairyGUI-Phaser/files/8509291/test.zip)

**Comment by akeboshi1** [comment]
> > > 1.提示文本导出不成功,得代码指定 2.输入看不到文字 ![demo](https://user-images.githubusercontent.com/37748815/163719564-28540829-fad3-44d4-9385-231ef59aecef.gif)
> > 
> > 
> > 提供下项目资源和demo 或代码
> > [test.zip](https://github.com/ApowoGames/FairyGUI-Phaser/files/8509291/test.zip)

实际操作后，我这边的显示：
![image](https://user-images.githubusercontent.com/18412751/163908911-5a2c84dc-3d70-4a61-ba16-8ea4cafffc83.png)
![image](https://user-images.githubusercontent.com/18412751/163908939-1cf3ec74-3d3c-4aa8-931f-abaefa763349.png)
全屏幕的代码最好不要调用，因为输入文本是dom元素，全屏之后，现阶段并没有做位置和尺寸大小的调整，如果你需要做适配的话，最好利用组件和父容器的关联，这边有两个方法是关联后做适配的计算
**externalSetSize(实际设备宽度，实际设备高度) 
externalSetScale(scaleX:设备dpr，scaleY:设备dpr，sceneType)**
sceneType为
export enum ScreenType {
    NONE,
    FULL,
    WIDTH,
    HEIGHT
}
下面为我项目的适配代码
![image](https://user-images.githubusercontent.com/18412751/163909666-914d65e1-73a0-4005-a174-3d6202b31bd3.png)

**Comment by 2505817596** [comment]
加入以下配置解决输入框输入问题
`const game = new Phaser.Game({
	//...
	dom: {
		createContainer: true
	},
      //...
});`

**Comment by 2505817596** [comment]
大佬,还有几个问题看看
1.提示文本导出不成功,得代码指定颜色,才会显示
2.输入框文本颜色不生效
3.密码显示模式没有生效
4.输入框聚焦问题,好像只要点击输入框以外的区域也会聚焦

**Comment by akeboshi1** [comment]
新分支上已经修复了不同分辨率下输入文本的交互区域问题

**Comment by akeboshi1** [comment]
> 大佬,还有几个问题看看 1.提示文本导出不成功,得代码指定颜色,才会显示 2.输入框文本颜色不生效 3.密码显示模式没有生效 4.输入框聚焦问题,好像只要点击输入框以外的区域也会聚焦

已经在新的分支上修复了这些问题，等我调整好适配的代码，合并到主分支即可
