### ISSUE TITLE
文本样式模版遇到的某些问题

### ISSUE THREAD

**Issue by 2505817596** [ApowoGames/FairyGUI-Phaser#5]
1.文本(GTextField | GRichTextField)模板功能没有生效

**Comment by akeboshi1** [comment]
> 1.文本(GTextField | GRichTextField)模板功能没有生效

请提供下你的demo或代码

**Comment by 2505817596** [comment]
https://github.com/ApowoGames/FairyGUI-Phaser/issues/4#issuecomment-1101928005

**Comment by 2505817596** [comment]
> > 1.文本(GTextField | GRichTextField)模板功能没有生效
> 
> 请提供下你的demo或代码

https://github.com/ApowoGames/FairyGUI-Phaser/issues/4#issuecomment-1101928899

**Comment by akeboshi1** [comment]
> > > 1.文本(GTextField | GRichTextField)模板功能没有生效
> > 
> > 
> > 请提供下你的demo或代码
> 
> [#4 (comment)](https://github.com/ApowoGames/FairyGUI-Phaser/issues/4#issuecomment-1101928899)

哦，看到了，下个版本更新会修复

**Comment by akeboshi1** [comment]
> > > 1.文本(GTextField | GRichTextField)模板功能没有生效
> > 
> > 
> > 请提供下你的demo或代码
> 
> [#4 (comment)](https://github.com/ApowoGames/FairyGUI-Phaser/issues/4#issuecomment-1101928899)

更新到 70版本解决此问题
