### ISSUE TITLE
使用组件扩展功能报错

### ISSUE THREAD

**Issue by 2505817596** [ApowoGames/FairyGUI-Phaser#6]
代码如下
![image](https://user-images.githubusercontent.com/37748815/164039683-054726df-46d0-4b75-9ecb-1f2f7d8814b7.png)
控制台信息
![image](https://user-images.githubusercontent.com/37748815/164039761-911a4ae9-2c62-42b7-a03c-83cf6a8ab661.png)

**Comment by akeboshi1** [comment]
> 代码如下 ![image](https://user-images.githubusercontent.com/37748815/164039683-054726df-46d0-4b75-9ecb-1f2f7d8814b7.png) 控制台信息 ![image](https://user-images.githubusercontent.com/37748815/164039761-911a4ae9-2c62-42b7-a03c-83cf6a8ab661.png)

看这报错信息，应该是scene不存在，首先确认下，scene是否传入到GRoot中

**Comment by 2505817596** [comment]
这里有传
![image](https://user-images.githubusercontent.com/37748815/164157816-978b3818-f06c-427f-83eb-46779005a382.png)

**Comment by akeboshi1** [comment]
> 代码如下 ![image](https://user-images.githubusercontent.com/37748815/164039683-054726df-46d0-4b75-9ecb-1f2f7d8814b7.png) 控制台信息 ![image](https://user-images.githubusercontent.com/37748815/164039761-911a4ae9-2c62-42b7-a03c-83cf6a8ab661.png)

![image](https://user-images.githubusercontent.com/18412751/168267329-49e8771a-afb7-470a-89e5-cc9402c0c9ce.png)
class A必须传入一个scene，后续的创建对象才能找到scene
加入容错，等待分支合并
